apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: nodejs-template
  title: NodeJS Service
  description: Template to create a NodeJS based Backstage service
spec:
  owner: backstage/demo
  type: service
  parameters:
      - title: Fill in some steps
        required:
          - name
          - description
        properties:
          name:
            title: Name
            type: string
            description: Unique name of the Service
          description:
            title: Description
            type: string
            description: Description of this Service
          owner:
            title: Owner
            type: string
            description: Owner of the component
            ui:field: OwnerPicker
            ui:options:
              catalogFilter:
                kind: Group
      - title: Choose a location
        required:
          - repoUrl
        properties:
          repoUrl:
            title: Repository Location
            type: string
            ui:field: RepoUrlPicker
            ui:options:
              requestUserCredentials:
                secretsKey: USER_OAUTH_TOKEN
                additionalScopes:
                  github:
                    - workflow
              allowedHosts:
                - github.com
              allowedOwners:
                - reneglavanovitsorg
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ../template-base
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
 
    - id: publish-repo
      name: Publish Repository
      action: publish:github
      input:
        gitAuthorName: ${{ user.entity.metadata.name }}
        gitAuthorEmail: ${{ user.entity.spec.profile.email }}
        repoUrl: ${{ parameters.repoUrl }}
        description: ${{ parameters.description }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}